### ISSUE TITLE
incompatible with shells started via 'exec shell' in ~/.bashrc

### ISSUE THREAD

**Issue by vede1** [purcell/exec-path-from-shell#49]
If a shell is started at the end of ~/.bashrc (e.g., `exec fish`), then it causes spacemacs to start with an error:
```
Error (use-package): exec-path-from-shell :init: Expected printf output from shell, but got: "bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
```

**Comment by purcell** [comment]
Yep, that's always going to cause problems. If you want the `fish` startup files to take effect (e.g. to set environment variables) then change your shell to `fish`. Otherwise, if you're correctly using `.bash_profile` or similar to set your environment variables, remove "-i" from `exec-path-from-shell-arguments` so that the `.bashrc` is not executed: this is recommended anyway.
