### ISSUE TITLE
run vim in emacs term mode

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [purcell/exec-path-from-shell#58]
I have tried to run vim in emacs many times
the result is also can't be satisfied for me
I check the variable in term mode `echo $TERM`
it print out `eterm-color`
then the same step for mac terminal `echo $TERM`
it print out `xterm-256color`

------------
something I already use this package to add TERM variable

**Comment by purcell** [comment]
`$TERM` allows the terminal program (e.g. `vim`) to look up the capabilities of the terminal it is running in. If you override it, it won't have the effect you want.

This is not a problem with `exec-path-from-shell`, because `term-mode` sets `$TERM` explicitly. If you want to change its value, modify the variable `term-term-name`.
