### ISSUE TITLE
`exec-path-from-shell-initialize` cannot work correctly.

### ISSUE THREAD

**Issue by VonFry** [purcell/exec-path-from-shell#78]
This package can work before updating. But it cannot work for me now. 

If I call `(exec-path-from-shell-initialize)`, having tried by both daemon and `ielm`, it looks like it has entered an endless loop for emacs, I cannot do anything in emacs.

These days I only update my macOS with a offical update on app store.

system os: `10.13.3 (17D102)` & `Darwin Vonfry.local 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64` 

emacs version: `GNU Emacs 25.3.1
Copyright (C) 2017 Free Software Foundation, Inc.
GNU Emacs comes with ABSOLUTELY NO WARRANTY.
You may redistribute copies of GNU Emacs
under the terms of the GNU General Public License.
For more information about these matters, see the file named COPYING.`

`$PATH`:  `/Users/vonfry/.opam/system/bin:/Users/vonfry/.local/bin:/Users/vonfry/.cabal/bin:/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/opt/llvm/bin:/usr/local/opt/curl/bin:/usr/local/opt/gnu-tar/libexec/gnubin:/usr/local/opt/sqlite/bin:/usr/local/opt/go/libexec/bin:/Users/vonfry/.zplug/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/aria2/bin:/usr/local/MacGPG2/bin:/opt/X11/bin:/usr/local/opt/fzf/bin:/usr/local/opt/ghc@8.0/bin`

<img width="1224" alt="2018-03-31 14 10 36" src="https://user-images.githubusercontent.com/3413119/38160259-4ea2c7ea-34ed-11e8-91e6-e37b3a179428.png">

**Comment by purcell** [comment]
Try setting `debug-on-quit` to `t`, then hit `C-g` while the command is hanging. You should get a backtrace. Also try setting `exec-path-from-shell-debug` to `t` first, which will cause debug output to be printed in `*Messages*`.

I'm confident the problem is in your Emacs configuration or shell configuration, though. In particular, if you have upgraded your Emacs version, you should reinstall all your packages (including `exec-path-from-shell`) because elisp bytecode is not portable between releases.

**Comment by VonFry** [comment]
Sorry, I have found the reason.

I have an error when updating macOS. After I have installed it again, all is fine.

**Comment by purcell** [comment]
Great! Glad you figured it out.
