### ISSUE TITLE
README suggestion

### ISSUE THREAD

**Issue by snehrbass** [purcell/exec-path-from-shell#99]
I launch emacs as a daemon and had to change my systemd startup process to point to a shell script to source my profile and rc files before launching the daemon. I feel like this fix would be useful to other if mentioned in the README.

**Comment by purcell** [comment]
Done, thank you.

**Comment by marlinstrub** [comment]
What is now mentioned in the readme already helps, but I'm not sure it fully covers @snehrbass' fix? For `exec-path-from-shell-initialize` to get my user's path I had to replace

`ExecStart=/path/to/emacs --daemon`

with

`ExecStart=/bin/bash -c 'source .bashrc; /path/to/emacs --daemon`

otherwise my user's local `bin` would not be included in the path. Maybe something along these lines would be helpful to add @purcell ?

**Comment by purcell** [comment]
> otherwise my user's local `bin` would not be included in the path. Maybe something along these lines would be helpful to add @purcell ?

If I'm understanding your comment correctly, aren't you suggesting I tell users to set things up so that they don't need this package? I feel like that's a little bit out of scope for this README.
